apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: no-requests
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Tensure/td-kyverno.git
    targetRevision: main
    path: apps/no-requests/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: no-requests
  syncPolicy:
    automated:
      prune: true
      selfHeal: true