apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: orphaned-deployments
  annotations:
    policies.kyverno.io/description: >-
      This policy will label deployments missing an owner label     
spec:
  rules:
  - name: orphaned-deployments
    match:
      any:
      - resources:
          kinds:
          - Deployment
    mutate:
      patchStrategicMerge:
        metadata:
          labels:
            +(orphaned): "true"
    preconditions:
        - key: "{{ request.object.metadata.labels.owner || '' }}"
          operator: Equals
          value: ""
